# This is a basic workflow to help you get started with Actions

name: Get the version of Python

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ candidate-name ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-on-container:
    runs-on: ubuntu-latest
    container:
      image: python:3.6-alpine3.12
    
    steps:
      - uses: actions/checkout@v2

      - name: get Python version
        run: python --version
      
      - name: list branches and current branch
        run: git status && echo $(git branch)
      

